version: "3"
services:
  samba:
    image: dperson/samba
    container_name: "SambaServer"
    restart: always
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - "/home/nas:/mnt/share"
    command: [
      "-r", "-p",
      "-s", "share;/mnt/public;yes;no;yes;all",
      "-u", "admin;admin"
    ]
